version: '3'
services:
  mysql:
    hostname: mysql
    image: mysql:latest
    volumes:
      - ./mysql/resource:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    tty: true
