version: '3'
services:
  mysql:
    hostname: mysql
    image: mysql:latest
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/conf/showProcesslist.sh:/etc/mysql/showProcesslist.sh
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    tty: true
